mislistudenta/main/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic.base import TemplateView
from main.views import *

urlpatterns = patterns('',
    url(r'^$', home, name='home'),
    url(r'^order', order),
    url(r'^subscribe/(?P<order_number>.*)', subscribe),
    url(r'^contacts', contacts, name='contacts'),
    url(r'^more', home, {'template': 'main/more.html'}, name='more'),
)
  

mislistudenta/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.base import TemplateView
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mislistudenta.views.home', name='home'),
    # url(r'^mislistudenta/', include('mislistudenta.foo.urls')),
    url(r'^', include('main.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns

mislistudenta/main/models.py
#-*-encoding:utf-8-*-
from django.db import models
from django.conf import settings
import datetime

DELIVERY_METHODS = (
    ('pickup', u'самовывоз'),
    ('courier', u'курьер'),
#    ('post', u'почта')
)

PAYMENT_METHODS = (
    ('cash', u'наличные'),
#    ('yandex', u'Яндекс.Деньги'),
)
class Customer(models.Model):
#    lastname = models.CharField(u"Фамилия", max_length=200)
#    firstname = models.CharField(u"Имя", max_length=200)
    name = models.CharField(u'Имя', max_length=200)
    email = models.EmailField("E-mail")
    tel = models.CharField(u"Телефон", max_length=20)
    city = models.CharField(u"Город", max_length=200, default=u'')
    address = models.CharField(u"Адрес", max_length=250, default=u'')
    subscribe = models.BooleanField(u"Подписка", default=True)

    def __unicode__(self):
        return u"%s (%s)" % (self.name, self.email)

    class Meta:
        verbose_name = u'Покупатель'
        verbose_name_plural = u'Покупатели'

class Book(models.Model):
    title = models.CharField(max_length=200)
    alias = models.CharField(max_length=64, unique=True)
    price = models.DecimalField(u'Цена', max_digits=9, decimal_places=2)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u'Книга'
        verbose_name_plural = u'Книги'

class Order(models.Model):
    customer = models.ForeignKey(Customer, related_name='orders', verbose_name=u'Покупатель')
    book = models.ForeignKey(Book, verbose_name=u'Книга')
    quantity = models.PositiveIntegerField(u"Количество")
    payment_method = models.CharField(u"Форма оплаты", max_length=200, choices=PAYMENT_METHODS)
    delivery_method = models.CharField(u"Вид доставки", max_length=200, choices=DELIVERY_METHODS)
    delivery_price = models.DecimalField(u"Стоимость доставки", max_digits=9, decimal_places=2, default=0)
    order_date = models.DateTimeField(u'Дата заказа')
    order_number = models.CharField(u'Номер заказа', max_length=20)
    amount = models.DecimalField(u'Стоимость', max_digits=9, decimal_places=2)

    def calc_total(self):
        return self.quantity * self.book.price + self.delivery_price

    @classmethod
    def calc_total2(cls, quantity=0, price=0, delivery_price=0):
        return quantity * price + delivery_price
    
    def __unicode__(self):
        return u"Заказ №%s" % self.order_number

    def save(self, *args, **kwargs):
        self.amount = self.quantity * self.book.price
        self.check_order_number()
        return super(Order, self).save(*args, **kwargs)

    def check_order_number(self):
        incr = 1
        while True:
            order_number = Order.objects.filter(order_number=self.order_number)
            if order_number:
                self.order_number = self.calc_order_number(incr)
                incr += 1
            else:
                break

    def calc_order_number(self, incr=None):
        if not self.order_date:
            self.order_date = datetime.datetime.now()
        order_number = u"%s%s от %s" % (
            self.order_date.strftime('%H%M'),
            (incr or ""),
            self.order_date.strftime('%d.%m.%y'))
        return order_number

    class Meta:
        verbose_name = u'Заказ'
        verbose_name_plural = u'Заказы'

mislistudenta/main/forms.py
#-*-encoding:utf-8-*-
from django import forms
from django.forms import ModelForm, TextInput, Select, HiddenInput
from main.models import Customer, Book, Order

verbose_name = lambda model, field_name: model._meta.get_field_by_name(field_name)[0].verbose_name

class OrderForm(forms.Form):
#    lastname = forms.CharField(
#            max_length=200,
#            label=verbose_name(Customer, 'lastname'),
#            widget=TextInput(attrs={'class': 'span4 validate[required,custom[onlyLetterSp]]'}))
#    firstname = forms.CharField(
#            max_length=200,
#            label=verbose_name(Customer, 'firstname'),
#            widget=TextInput(attrs={'class': 'span4 validate[required,custom[onlyLetterSp]]'}))
    name = forms.CharField(
            max_length=200,
            label=verbose_name(Customer, 'name'),
            widget=TextInput(attrs={'class': 'span4 validate[required,custom[onlyLetterSp]]', 'placeholder': u'Ваше имя'}))
    email = forms.EmailField(
            label=verbose_name(Customer, 'email'),
            widget=TextInput(attrs={'class': 'span4 validate[required,custom[email]]', 'placeholder': u'mail@example.com'}))
    tel = forms.CharField(
            max_length=20,
            label=verbose_name(Customer, 'tel'),
            widget=TextInput(attrs={'class': 'span4 validate[required,custom[phone]]', 'placeholder': u'Например: +7(999)123-45-67'}))
    quantity = forms.IntegerField(
            label=verbose_name(Order, 'quantity'),
            widget=TextInput(attrs={'class': 'span4 validate[required,min[1],max[100],custom[integer]'}))
    payment_method = forms.ChoiceField(
            label=verbose_name(Order, 'payment_method'),
            widget=Select(attrs={'class': 'span4 validate[required]'}),
            choices=Order._meta.get_field_by_name('payment_method')[0].choices)
    delivery_method = forms.ChoiceField(
            label=verbose_name(Order, 'delivery_method'),
            widget=Select(attrs={'class': 'span4 validate[required]'}),
            choices=Order._meta.get_field_by_name('delivery_method')[0].choices)
    city = forms.CharField(
            required=False,
            max_length=200,
            label=u"Город доставки",
            widget=TextInput(attrs={'class': 'span4 validate[required,custom[onlyLetterSp]]', 'placeholder': u'Москва'}))
#            widget=Select(attrs={'class': 'span4 validate[required]'}),
#            choices=(('', '---------'), (u'Москва', u'Москва')))
    address = forms.CharField(
            required=False,
            max_length=200,
            label=u"Адрес доставки",
            widget=TextInput(attrs={'class': 'span4 validate[required]', 'placeholder': u'ул. Примерная, д. 1, кв. 1'}))
    book = forms.CharField(
            max_length=200,
            label=u"Ежедневник",
            widget=HiddenInput())

mislistudenta/main/views.py
#-*-encoding:utf-8-*-
from django.core.exceptions import ObjectDoesNotExist
from django.template import RequestContext
from django.shortcuts import render
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.core.context_processors import csrf
from main.forms import OrderForm
from main.models import Customer, Order, Book
from django.utils import simplejson
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from smtplib import SMTPException
from django.utils.html import strip_tags
from django.conf import settings
import datetime
from urlparse import parse_qsl
from urllib2 import unquote
from decimal import Decimal


def home(request, template=settings.MAIN_TEMPLATE):
    context = {}
    try:
        context['white_price'] = Book.objects.get(alias='white').price
        context['red_price'] = Book.objects.get(alias='red').price
        context['blond_price'] = Book.objects.get(alias='blond').price
        now = datetime.datetime.now()
        today = datetime.date(year=now.year, month=now.month, day=now.day)
        context['today'] = today
        today_orders = Order.objects.filter(
            order_date__gte=today).order_by(
            '-order_date')
        context['last_order_number'] = today_orders and today_orders[0].order_number.split()[0]
    except ObjectDoesNotExist:
        pass
#    context['order_form'] = OrderForm()
#    template = settings.MAIN_TEMPLATE
    return render(request, template, context)

def order(request):
    context = {}
    context.update(csrf(request))
    template = "main/order_dialog_step1.html"
    if request.method == 'POST':
        step = request.POST.get('step', '1')
        form = OrderForm(request.POST)
        if form and form.is_valid():
            if step == '1': # form -> preview
                try:
                    book = Book.objects.get(alias=form.cleaned_data['book'])
                except ObjectDoesNotExist:
                    response = simplejson.dumps({"success": False})
                    return HttpResponse(response,
                        content_type="application/javascript; charset=utf-8")
                context['book'] = book
                context['check_form'] = form
                context['total'] = Order.calc_total2(
                    quantity=form.cleaned_data['quantity'],
                    price=book.price,
                    delivery_price=Decimal(settings.DELIVERY_PRICE)
                        if form.cleaned_data['delivery_method'] == 'courier' else 0)
                template = "main/order_dialog_step2.html"
                success = True
            elif step == '2': # preview -> submit
                success = True
                customer = Customer()
                order = Order()
#                customer.lastname = form.cleaned_data['lastname']
#                customer.firstname = form.cleaned_data['firstname']
                customer.name = form.cleaned_data['name']
                customer.email = form.cleaned_data['email']
                customer.tel = form.cleaned_data['tel']
                customer.city = form.cleaned_data['city']
                customer.address = form.cleaned_data['address']
                customer.save()
                order.book = Book.objects.get(alias=form.cleaned_data['book'])
                order.quantity = form.cleaned_data['quantity']
                order.payment_method = form.cleaned_data['payment_method']
                order.delivery_method = form.cleaned_data['delivery_method']
                if order.delivery_method == 'courier':
                    order.delivery_price = Decimal(settings.DELIVERY_PRICE)
                order.order_date = datetime.datetime.now()
                order.order_number = order.calc_order_number()
                order.customer = customer
                order.save()
                context['order'] = order
                context['total'] = order.calc_total()
                template = "main/order_dialog_finish.html"
                email_html_content = render_to_string('main/confirmation.html',
                                                      RequestContext(request, context))
                email_text_content = strip_tags(email_html_content)
                for destination in [order.customer.email, settings.DELIVERY_EMAIL]:
                    msg = EmailMultiAlternatives(u'Заказ на mislistudenta.ru',
                                                 email_text_content,
                                                 "mislistudenta.ru <%s>" % settings.EMAIL_HOST_USER,
                                                 [destination])
                    msg.attach_alternative(email_html_content, 'text/html')
                    try:
                        msg.send()
                    except SMTPException as e:
                            msg = u"Error: %s\nDestination: %s\nOrder number: %s" % (e, destination, order.order_number)
                            send_mail('[Django] Error in e-mail sending',
                                  msg,
                                  '',
                                  [mail[1] for mail in settings.ADMINS],
                                  auth_user=settings.ADMIN_HOST_USER,
                                  auth_password=settings.ADMIN_HOST_PASSWORD)
        else:
            form._errors = {}
            context["order_form"] = form
            success = False
    else:
        form = request.GET.get('form')
        if form:
            form = unquote(request.GET.get('form').encode('utf8')).decode('utf8')
            context["order_form"] = OrderForm(initial=dict(parse_qsl(form)))
        else:
            context["order_form"] = OrderForm()
        context['delivery_price'] = settings.DELIVERY_PRICE
        success = True
    html = render_to_string(template, RequestContext(request, context))
    response = simplejson.dumps({"success": success, "html": html})
    return HttpResponse(response,
                        content_type="application/javascript; charset=utf-8")

def contacts(request):
    return render(request, "main/contacts.html", {})

def subscribe(request, order_number):
    if request.method == 'POST':
        subscribed = request.POST.get('subscribed', True)
        order = Order.objects.filter(order_number=order_number)
        if order:
            customer = order[0].customer
            customer.subscribe = True if subscribed == 'true' else False
            customer.save()
        response = ""
        return HttpResponse(response,
                        content_type="application/javascript; charset=utf-8")
    return HttpResponse("",
                        content_type="application/javascript; charset=utf-8")

mislistudenta/templates/main/base.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Мысли студента</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta property="og:title" content="mislistudenta.ru">
    <meta property="og:description" content="mislistudenta.ru">
    <meta property="og:url" content="http://mislistudenta.ru">
    <meta property="og:image" content="http://mislistudenta.ru/static/smile.png">
    <meta property="og:type" content="book">
    <meta property="vk:app_id" content="2636882" />
{#    google apps verification#}
    <meta name="google-site-verification" content="_lAhxeJFZ8IcbobLCl_LwpmTSz-DQNXj4EqgYxX83Gk" />
    <!-- vkontakte -->
{#    <script type="text/javascript" src="http://userapi.com/js/api/openapi.js?34"></script>#}
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

    <!-- Le styles -->

{#	<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">#}
{#    <link rel="stylesheet/less" href="{{ STATIC_URL }}less/bootstrap.less" media="all">#}
    <link rel="stylesheet" href="{{ STATIC_URL }}js/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" type="text/css" media="screen" />

{#    <link rel="stylesheet/less" href="static/style.less">#}
{#	<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>#}

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
		<!--<script>window.jQuery || document.write('<script src="/static/bootstrap/js/jquery-1.6.2.min.js"><\/script>')</script>-->
		<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
        <script src="http://lesscss.googlecode.com/files/less-1.1.3.min.js"></script>
        <script src="{{ STATIC_URL }}js/bootstrap-modal.js"></script>
        <script src="{{ STATIC_URL }}js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
		{% block javascript %}{% endblock %}

    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-26204153-1']);
        _gaq.push(['_setDomainName', 'mislistudenta.ru']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
  </head>

  <body>
{#    <img id="lenta-right" src="{{ STATIC_URL }}images/lenta-right.png">#}
    <div id="content" class="container">
			{% block content %}{% endblock %}
    </div> <!-- /container -->
    <div id="contacts" class="modal hide fade">
        <div class="modal-header">
            <a href="#" class="close">&times;</a>
            <h3>Контакты</h3>
        </div>
        <div class="modal-body">
            <p><strong>Адрес:</strong> г. Москва, Кривоколенный переулок, д. 5, стр. 4, 2 этаж, офис
232 (типография Business Copy)
            <p><strong>Метро:</strong> м. Лубянка (м. Кузнецкий Мост), м. Чистые пруды
(м. Тургеневская)</p>
            <p><strong>Телефон:</strong> +7 (499) 409-8209</p>
            <p><strong>E-mail:</strong> info<img class="icon" src="{{ STATIC_URL }}images/at.png">mislistudenta.ru</p>
            <img id="map" src="http://static-maps.yandex.ru/1.x/?ll=37.63325,55.762599&z=15&l=map&size=474,354&pt=37.634452,55.761462,pmlbm&key=ADaUlU4BAAAAQk9aCgIAVtDlNdHH7Q-522SPXqPL3WkyKhQAAAAAAAAAAAAVXs8O2oM-O_u6NzDE69cN3ajBaA==&wizard=constructor" alt="Карта"/>
        </div>
    </div>
    <footer class="footer">
        <div class="container">
            <div id="social" class="row">

        <div class="span16">
{#             <div id="fb-root"></div>#}
{#            <script>(function(d, s, id) {#}
{#                var js, fjs = d.getElementsByTagName(s)[0];#}
{#                if (d.getElementById(id)) {return;}#}
{#                js = d.createElement(s); js.id = id;#}
{#                js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";#}
{#                fjs.parentNode.insertBefore(js, fjs);#}
{#            }(document, 'script', 'facebook-jssdk'));</script>#}
{#            <div class="fb-like" data-href="mislistudenta.ru" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false" data-font="arial"></div>#}
{#            #}
{#            <div id="vk_like"></div>#}
{#            <script type="text/javascript">#}
{#                VK.Widgets.Like("vk_like", {type: "button", width: "60"});#}
{#            </script>#}
            <script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
            <div class="social_back">
            <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="none" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj"></div>
            </div>
        </div>
    </div>
            <p></p>
            <p class="copyright">All rights! Reserved <img class="icon" src="{{ STATIC_URL }}images/smile-brown.png" alt=":-)"/> seamless</p>
            <nav id="footer_nav">
                <ul>
                    <li><a href="{% url home %}" class="btn nav_btn">Главная</a></li>
                    <li><a href="#" data-controls-modal="contacts" class="btn nav_btn" data-keyboard="true" data-backdrop="true">Контакты</a></li>
                    <li><a href="{% url more %}" class="btn nav_btn">Хочу еще</a></li>
                </ul>
            </nav>
        </div>
    </footer>
  </body>
</html>

mislistudenta/templates/main/confirmation.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=utf-8">
  <title></title>
</head>
<body>
<pre style="font-size: 12pt">
Здравствуйте, {{ order.customer.name }}!

Подтверждаем Ваш заказ:

Номер заказа           :  {{ order.order_number }}
Наименование товара    :  Ежедневник "{{ order.book }}"
Количество             :  {{ order.quantity }} шт.
{% if order.delivery_method != 'pickup' %}Доставка               :  {{ order.delivery_price|stringformat:"d" }} руб.{% else %}Самовывоз              :  адрес для самовывоза
г. Москва, Кривоколенный переулок, д. 5, стр. 4, 2 этаж, офис 232 (типография Business Copy)
(м. Тургеневская или м. Лубянка)
Просим Вас осуществить самовывоз в удобное для Вас время ежедневно с 10:00 до 20:00.
Наш контактный телефон :  +7 (499) 409-8209
Ваш контактный телефон :  {{ order.customer.tel }}{% endif %}
{% if order.delivery_method != 'pickup' %}Адрес доставки         :  {{ order.customer.city }}, {{ order.customer.address }}
Контактный телефон     :  {{ order.customer.tel }}
Мы Вам позвоним, чтобы уточнить детали доставки.
Наш контактный телефон :  +7 (499) 409-8209
{% endif %}
-------------------------------------------
Общая стоимость        :  {{ total|stringformat:"d" }} руб.
Оплата                 :  наличные

С вашего разрешения мы напечатаем еще несколько замечательных книг.
Делать что-то хорошее это так естественно. Интересно узнать ваши
мысли.
info@mislistudenta.ru
Спасибо.

P.S. Студенческие годы - это мега сексуально, не так ли?
</pre>
<p style="color: blue; font-size: 11pt; font-family: monospace">
seamless<img height="10" src="http://mislistudenta.ru{{ STATIC_URL }}images/smile-blue.png">. coming soon. winter <span style="font-size: 7.5pt;">2014</span>.
</p>
{% if order.delivery_method == 'pickup' %}
<pre style="font-size: 12pt">
Схема проезда:
<img src="http://static-maps.yandex.ru/1.x/?ll=37.63325,55.762599&z=15&l=map&size=474,354&pt=37.634452,55.761462,pmlbm&key=ADaUlU4BAAAAQk9aCgIAVtDlNdHH7Q-522SPXqPL3WkyKhQAAAAAAAAAAAAVXs8O2oM-O_u6NzDE69cN3ajBaA==&wizard=constructor">
</pre>
{% endif %}
</body>
</HTML>

mislistudenta/templates/main/contacts.html
{% extends "main/base.html" %}

mislistudenta/templates/main/home_1.html
{% extends "main/base.html" %}
{% load bootstrap %}
{% load main_extras %}
{% block javascript %}
{#    <script src="{{ STATIC_URL }}js/bootstrap-alerts.js"></script>#}
    <script src="{{ STATIC_URL }}js/jquery.validationEngine-ru.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.validationEngine.js"></script>
    <script src="{{ STATIC_URL }}js/script.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/validationEngine.jquery.css" type="text/css"/>
{% endblock %}
{% block content %}
    <div class="row">
        <div id="order_num" class="span16">
            <p class="pull-right">{% if last_order_number %}За {{ today|date:"d.m.y" }} оформлен уже {{ last_order_number }} заказ.{% endif %}</p>
        </div>
    </div>
    <div class="row first_content_row">
        <div class="span6 offset2">
            <h5 class="caption">КНИГИ ДЛЯ ТЕХ, КТО БЫЛ, ЕСТЬ И БУДЕТ СТУДЕНТОМ</h5>
        </div>
        <div class="span7">
            <h5 class="caption">ИНТЕРЕСНО, ПОЧУВСТВУЕТЕ ЛИ ВЫ УДИВЛЕНИЕ, ОБНАРУЖИВ</h5>
        </div>
    </div>
    <div class="main row">
        <div class="span6 offset2">
            <div id="verse1">
                <h3 class="hide"></h3>
                <p>Студентом быть!<br>
                Так круто! Кайф!<br>
                </p>
                <p>
                В такие годы: мечтай, студент!<br>
                И думай, обо всем на свете.<br>
                </p>
                <p>
                Но вот беда!<br>
                Известны мысли эти.<br>
                Но эти слова три, решают все!<br>
                Как ни крути.<br>
                Интрига? Да-а.<br>
                Так покупай, читай, пиши.<br>
                </p>
            </div>

        </div>
        <div class="span8">
            <div class="row">
                <div class="span5 book_cont1">
                    <a id="white_book" class="book_link" href="{{ STATIC_URL }}images/maket_white_big.png">
                        <img class="big_book" src="{{ STATIC_URL }}images/maket_white_small.png" alt="">
                    </a>
                </div>
{#                <div class="span5 book_cont">#}
{#                    <a id="red_book" class="book_link" href="{{ STATIC_URL }}images/maket_red_big.png">#}
{#                        <img class="book" src="{{ STATIC_URL }}images/maket_red_small.png" alt="">#}
{#                    </a>#}
{#                </div>#}
            </div>
            <div id="price_row" class="row">
                <div class="span5 offset1">
                    <span class="price">{{ white_price|stringformat:"d руб." }}</span>
                    <a id="buy_white" class="buy_btn btn large" href="#">КУПИТЬ</a>
                </div>
{#                <div class="span5">#}
{#                    <span class="price">{{ red_price|stringformat:"d руб." }}</span>#}
{#                    <a id="buy_red" class="buy_btn btn large" href="#">КУПИТЬ</a>#}
{#                </div>#}
            </div>
        </div>
    </div>

    

    <div id="order_dialog" class="modal hide fade">
        <div class="content">
        <!--{% include "main/order_dialog_step1.html" %}-->
        </div>
    </div>

    <div id="book_preview" class="modal hide fade">
{##}
{#        <div class="modal-header">#}
{#            <a href="#" class="close">&times;</a>#}
{#            <p>&nbsp;</p>#}
{#        </div>#}
        <div class="modal-body">
        <p><a href="#" class="close">&times;</a></p>
        <img>
        </div>
    </div>
{% endblock %}

mislistudenta/templates/main/order_dialog_finish.html
<div class="modal-header">
    <a href="#" class="close" title="Закрыть">&times;</a>
    <h3>Готово</h3>
</div>
<div class="modal-body">
    <h3>Уважаемый клиент!</h3>
    <ul class="unstyled order_details">
        <li><span class="order_details_label">Номер заказа</span>: <strong id="order_number">{{ order.order_number }}</strong>.</li>
        <li><span class="order_details_label">Стоимость</span>: <strong>{{ total|stringformat:"d" }}</strong> руб.</li>
        <li><span class="order_details_label">Форма оплаты</span>: <strong>{{ order.get_payment_method_display }}</strong>.</li>
        <li>Подтверждение заказа направлено на {{  order.customer.email }}.</li>
    </ul>
    <p>

        <input type="checkbox" id="subscribe" name="subscribe" checked="true">
        <span>хочу узнавать новое</span>
    
    </p>
    <p>
        Благодарим вас за покупку.
    </p>
</div>
<div class="modal-footer">
    <div class="row">
    <p class="pull-right"><em>Мысли проактивно</em></p>
    </div>
    <a href="" id="order_dialog_btn_finish" class="btn primary"><img src="{{ STATIC_URL }}images/smile-white.png">K</a>
</div>

mislistudenta/templates/main/order_dialog_step1.html
{% load bootstrap %}
<div class="modal-header">
    <a href="#" class="close" title="Закрыть">&times;</a>
    <h3>Заполните поля заказа</h3>
</div>
<div class="modal-body">
    <form id="order_form">
        {% csrf_token %}
        {{ order_form|bootstrap }}
        <div id="delivery_price" class="hide" data-delivery_price={{ delivery_price }}></div>
        <input type="hidden" name="step" value="1" />
    </form>
</div>
<div class="modal-footer">
    <button id="order_dialog_btn_step1" class="btn primary">Далее</button>
</div>